### ISSUE TITLE
Add or Change Options of the chart

### ISSUE THREAD

**Issue by Puerco-Potter** [mbo2olivier/MukadiChartJSBundle#2]
This is not clear or maybe not suported by the builder, but after going over the code I get how to do it and I post this here in the case someone would need it.

    //Build the chart
    $chart = $builder->buildChart('Name',Chart::BAR);
    //then add or override the options. In this example I remove the onClick behavior of legend
    $chart -> pushOptions([
            'legend' => [
                'onClick' => null 
            ]
    ]);

I am pretty gratefull for this bundle, it makes the chart generation easy on symfony. This is just an overlook.

**Comment by mbo2olivier** [comment]
Thank you for emphasizing it. This is an unfortunate omission, I planned to complete the doc but I never find time.
Thank you for the attention paid to my modest work.
p.s: sorry for my language, i'm not fluent in english.

**Comment by mbo2olivier** [comment]
the missing documentation was added in the [chartjs-builder](https://github.com/mbo2olivier/mukadi-chartjs-builder) page.

**Comment by Puerco-Potter** [comment]
Awesome, I feel like I helped hahaha
